version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  nodeapp:
    build: .
    container_name: nodeapp_container
    ports:
      - "8080:8080"
    environment:
      HOST_PATH: 0.0.0.0
      MONGODB_PATH: mongodb://root:example@mongodb_container:27017/
    depends_on:
      - mongo
    networks:
      - mynetwork

volumes:
  mongo-data:


networks:
  mynetwork:
